Add a summary table into secret manager
dotnet/dnceng pull request #314
Opened 2023-06-29 08:36 UTC by premun

https://github.com/dotnet/dnceng/issues/309

2023-06-29 11:06 UTC, oleksandr-didyk submitted a review, later dismissed

2023-06-29 23:38 UTC, dougbu requested changes

2023-06-29 23:38 UTC, dougbu commented on src/SecretManager/Microsoft.DncEng.SecretManager.Tests/SynchronizeCommandTests.cs
> +            "test",
the minor formatting and whitespace changes in this PR make it _much_ more difficult to see the meat of the work. please do anything more than the core changes and perhaps trailing whitespace trimming (which is easy to ignore in GitHub) in separate PRs

2023-06-29 23:38 UTC, dougbu commented on src/SecretManager/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
> +            _console.WriteLine($"📄 Synchronizing secrets contained in {_manifestFile}");
what's the new character here❔ I can't read what it's trying to indicate. was its addition intentional❔

2023-06-29 23:38 UTC, dougbu commented on src/SecretManager/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
> +            var problems = new List<(string, string)>();
nit: unnamed tuples make code less readable
```suggestion
            var problems = new List<(string name, string problem)>();
```

2023-06-29 23:38 UTC, dougbu commented on src/SecretManager/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
> +                var summaryStatus = (Status: string.Empty, Icon: string.Empty);
nit: again, please name the tuple values

2023-06-29 23:38 UTC, dougbu commented on src/SecretManager/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
> +                    table.AddRow(name, string.Empty, "⚠️", "Extra secret");
you don't have the secret type available here❔

2023-06-29 23:38 UTC, dougbu commented on src/SecretManager/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
> +            _console.WriteLine("🔥 Detected additional problems:");
suggest checking whether `problems` is empty. skip this output if so

2023-06-30 07:45 UTC, premun commented on src/SecretManager/Microsoft.DncEng.SecretManager.Tests/SynchronizeCommandTests.cs
> +            "test",
Whitespace changes can be turned off here:

![image](https://github.com/dotnet/dnceng/assets/7013027/7ea27419-1325-4d4f-afca-be9cfad98d90)

Does that work for you?

2023-06-30 07:47 UTC, premun commented on src/SecretManager/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
> +            _console.WriteLine($"📄 Synchronizing secrets contained in {_manifestFile}");
I added this as a visual queue that a new keyvault is started to be processed.

One of the problems I have with the logs is to figure out which keyvault the problematic secret is from so I am looking for this log line a lot.

2023-06-30 07:48 UTC, premun commented on src/SecretManager/Microsoft.DncEng.SecretManager.Tests/SynchronizeCommandTests.cs
> +            "test",
All whitespace (not just trailing) can be actually turned off. The tests were quite hard to read for me so I took the liberty but I can revert this file

2023-06-30 07:50 UTC, premun commented on src/SecretManager/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
> +                var summaryStatus = (Status: string.Empty, Icon: string.Empty);
These already have a name

2023-06-30 07:51 UTC, premun commented on src/SecretManager/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
> +                    table.AddRow(name, string.Empty, "⚠️", "Extra secret");
Just name, the expires-on tag and possibly other tags.

2023-06-30 07:55 UTC, premun commented on Directory.Packages.props
> +    <PackageVersion Include="ConsoleTables" Version="2.4.2" />
Yes we do, but I checked/know this exact one before using it. The source code is public, the owner is a guy from the JetBrains Rider I know and the source code is a single `.cs` file:
https://github.com/khalidabuhakmeh/ConsoleTables/blob/master/src/ConsoleTables/ConsoleTable.cs

2023-06-30 17:08 UTC, dougbu approved these changes

2023-06-30 17:08 UTC, dougbu commented on Directory.Packages.props
> +    <PackageVersion Include="ConsoleTables" Version="2.4.2" />
alright. do we have a process for confirming use of 3rd party packages within the group❔ product teams tend to require an escalation before taking new external dependencies.

2023-06-30 17:08 UTC, dougbu commented on src/SecretManager/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
> +                                var message = $"Missing {AzureKeyVault.NextRotationOnTag} tag, using the end of time as value";
Message is now incorrect. Should be reporting the problem parsing the value, ideally logging `nextRotationOn` as it did before.

2023-06-30 17:08 UTC, dougbu requested changes
oops

2023-06-30 17:10 UTC, dougbu commented on src/SecretManager/Microsoft.DncEng.SecretManager.Tests/SynchronizeCommandTests.cs
> +            "test",
I'm fully aware of that feature. it doesn't cover rewrapping lines or going from no indentation to some. thanks for reverting changes here

2023-06-30 17:12 UTC, dougbu commented on src/SecretManager/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
> +            _console.WriteLine($"📄 Synchronizing secrets contained in {_manifestFile}");
my point was mostly that the character is hard to discern and meant nothing to me. if it means something to you 🆗 but you may want to find something else

2023-07-03 07:48 UTC, premun commented on Directory.Packages.props
> +    <PackageVersion Include="ConsoleTables" Version="2.4.2" />
No, I don't think we don't but internal tooling is in a different boat than code that ends up in the product?

2023-07-03 07:55 UTC, premun commented on src/SecretManager/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
> +            _console.WriteLine($"📄 Synchronizing secrets contained in {_manifestFile}");
Ah, yeah, no I can look for something else. The message is about opening a manifest file, so I put there a file emoji

2023-07-03 07:56 UTC, premun commented on src/SecretManager/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
> +                                var message = $"Missing {AzureKeyVault.NextRotationOnTag} tag, using the end of time as value";
Ah, good catch

2023-07-03 07:59 UTC, premun commented on src/SecretManager/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
> +            _console.WriteLine($"📄 Synchronizing secrets contained in {_manifestFile}");
I put the one for "synchronization" 🔁 same as is used when a secret gets rotated. Should be more visible.

2023-07-06 16:39 UTC, missymessa commented on Directory.Packages.props
> +    <PackageVersion Include="ConsoleTables" Version="2.4.2" />
I don't have an issue with using this package, and I would imagine that we'd get CG warnings if there were issues with it. 

/cc @garath and @riarenas for opinions. 

@dougbu if you think we should have a formalized process for taking in new 3rd party dependencies, would you mind driving that process?

2023-07-06 16:40 UTC, missymessa approved these changes
LGTM ![shipit](https://cultofthepartyparrot.com/parrots/shipitparrot.gif)

2023-07-06 18:12 UTC, dougbu approved these changes
I should have updated my review after you fixed the incorrect message @premun. We can discuss 3rd party dependencies outside this PR&hellip;

2023-07-06 18:14 UTC, dougbu commented
Now GitHub is doing the "last reviewer" dance 😦 I can't approve this and bet your vote was reset @missymessa

2023-07-06 18:14 UTC, dougbu approved these changes

2023-07-06 18:16 UTC, dougbu commented
> I can't approve this

Weird, GitHub let me approve after telling me someone other than the last committer must approve. I'll enable auto-merge.

@AlitzelMendez any idea why there are two `Build Analysis` checks running on this PR❔

2023-07-06 18:19 UTC, missymessa commented
> > I can't approve this
> 
> Weird, GitHub let me approve after telling me someone other than the last committer must approve. I'll enable auto-merge.
> 
> @AlitzelMendez any idea why there are two `Build Analysis` checks running on this PR❔

One is on staging and the other is on prod. We use our own repos to dogfood staging.

2023-07-06 18:22 UTC, dougbu commented
> > @AlitzelMendez any idea why there are two Build Analysis checks running on this PR❔

> One is on staging and the other is on prod. We use our own repos to dogfood staging.

Ah, thanx for the explanation.

----

@Should we enable auto-merge to avoid further merge-from-main requirements❔

2023-07-06 18:24 UTC, missymessa commented
I don't think that auto-merge is preferable. I ended up turning that off the Maestro PRs, even.

2023-07-06 18:25 UTC, merged