Adding Chatbot Dashboard
dotnet/dnceng pull request #3814
Opened 2024-08-15 00:39 UTC by kalebfikadu

**Related Issue**
[https://github.com/dotnet/dnceng/issues/3215](url)

**Purpose**
* Provide engineering team with real-time view of the chatbot's performance
* Helps in identifying issues early and quickly ensuring that the Chatbot is operating correctly

**How to use**
* Navigate to Grafana instance
* Import the DNCEngChatBot.dashboard.json file
* The dashboard is available underneath the "arcade-services" folder

2024-08-15 17:40 UTC, missymessa commented
@garath I understand wanting to keep the Grafana dashboard with the place the service lives (dnceng repo), however, this looks like it's going into the arcade-services Grafana dashboard. Was that what you intended? 

@premun is it alright with ProdCon for a dashboard not related to ProdCon to be in the arcade-services Grafana dashboard?

2024-08-15 18:21 UTC, garath commented
It goes into a Grafana folder named Arcade Services, yeah.  I believe it just wasn't renamed after the repository was split and renamed. It can be changed.

2024-08-15 23:15 UTC, garath commented on src/Monitoring/Monitoring.ArcadeServices/parameters.json
> +    "Name": "PLACEHOLDER:a125b15a-7109-45b6-aa71-ddf4cfa05770",
What's this? I do not expect any "placeholder" or GUID-type entries.

2024-08-15 23:17 UTC, garath commented on src/Monitoring/Monitoring.ArcadeServices/parameters.json
> +    "Name": "PLACEHOLDER:a125b15a-7109-45b6-aa71-ddf4cfa05770",
I don't see it in the dashboard JSON. Perhaps this i sjust a leftover? If so it can probably just be deleted. (But double-check me - t is awkward to search in this interface.)

2024-08-15 23:17 UTC, garath requested changes
Looks like there's one last placeholder to deal with.

2024-08-16 07:20 UTC, premun commented
> @premun is it alright with ProdCon for a dashboard not related to ProdCon to be in the arcade-services Grafana dashboard?

@missymessa I am not sure how much I care but can you help me understand why? Why don't we just put it under another folder? It's just a configuration of paths so I am not clear what's the benefit of clumping it like this. It will be confusing people every now and then from now on.

2024-08-19 20:14 UTC, garath commented on src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/DNCEngChatbot.dashboard.json
> +          "subscription": "[parameter(84a65c9a-787d-45da-b10a-3a1cefce8060)]"
This isn't listed in the parameters file, which is an error.

2024-08-19 21:47 UTC, garath approved these changes

2024-08-19 21:54 UTC, missymessa approved these changes
LGTM ![shipit](https://cultofthepartyparrot.com/parrots/shipitparrot.gif)

2024-08-19 21:55 UTC, merged